config/routes.rb
SampleApp::Application.routes.draw do
 
  resources :users do
    member do
      get :following, :followers
    end
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :microposts, only: [:show, :index, :create, :update, :destroy]
    end
    namespace :v2 do
      resources :microposts, only: [:show,:index, :create, :update, :destroy]
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/loginin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/logout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contacts', to: 'static_pages#contacts', via: 'get'
  

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

	# 
	# callbacks/declarative
	# 
	before_action :get_user, 			only: [:edit, :update]
	before_action :valid_user,			only: [:edit, :update]
 	before_action :check_expiration, 	only: [:edit, :update]
  
	# 
	# on click of forgottem password link
	# 
	def new
	end

	# 
	# on submit of forgottem password email address form
	# 
	def create
		email = params[:password_resets][:email].downcase
		@user = User.find_by(email: email)	

		if @user
			@user.create_reset_digest
			@user.send_password_reset_email
			flash[:info] = "Password reset confirmation sent to #{@user.email}."
			redirect_to root_url
		else
			flash[:danger] = "Specified email, #{email}, not found!"
			render new_password_reset_path
		end 
	end

	# 
	# called from mail link
	# NOTE: reset token only available in form params reliably
	# 
	def edit
  	end

	# 
  	# on submit of ../password_resets/edit.html.erb form
  	# 
  	def update
  		if password_blank? 
  			flash.now[:danger] = "Password reset failed - password blank!"
  			render 'edit'
  		elsif @user.reset_password(user_params)
  			sign_in @user
  			flash[:success] = "Password reset successfully!"
  			redirect_to @user
  		else
  			# form error, no flash should be displayed
  			render 'edit'
  		end	
  	end

private

	def user_params
		params.require(:user).permit(:password, :password_confirmation)
	end

	def password_blank?
 		params[:user][:password].blank?
	end

	def get_user
		@user = User.find_by(email: params[:email])
	end

	def valid_user
		unless (@user && 
			@user.activated? && 
			@user.authenticated?(:reset, params[:id])
				)
			flash[:error] = "Password reset failed - invalid, unactivated or unauthenticated user!"
			redirect_to root_url
		end
	end

	def check_expiration
		if @user.password_reset_expired?
			flash[:danger] = "Password reset failed - time limit expired!"
			redirect_to root_url
		end
	end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Password Reset') %>
<h1>Password reset</h1>
<h2> for <%= @user.name %></h2>
<div class="row">
  	<div class="span6 offset3">	
	<%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

		<%= hidden_field_tag :email, @user.email %>

 		<%= f.label :password %>
		<%= f.password_field :password, class: "form-control" %>
		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation, class: "form-control" %>
		<%= f.submit "Reset Now", class: "btn btn-large btn-primary", style: "width: 100%;" %>
	<% end %>
	</div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, 'Forgotten Password') %>
<h1>Forgotten password</h1>

<div class="row">
  	<div class="span6 offset3">
	<%= form_for(:password_resets, url: password_resets_path) do |f| %>

		<%= f.label :email %>
		<%= f.email_field :email, class: "form-control" %>	

		<%= f.submit "Submit reset request", class: "btn btn-large btn-primary", style: "width: 100%;" %>

		<% end %>
	</div>
</div>